title: Suzielli Mendonça
#logo: /images/profile_picture.png
description: Physicist | Data Science | Data Analysis | Quantum Computing | Machine Learning | Time Series 
#show_downloads: true
theme: jekyll-theme-minimal
